ci: update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,75 +5,46 @@ on:
     branches:
       - master
 jobs:
-  Build-NodeJS:
+  release:
     runs-on: ubuntu-latest
+    environment: Production
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '22'
-          cache: 'yarn'
+          node-version: "22"
+          cache: "yarn"
       - name: Install dependencies
         run: yarn install --frozen-lockfile
-      - name: Run lint
-        run: yarn lint
       - name: Build project
         run: yarn build
-      - name: Prepare artifacts
+      - name: Collect files
         run: |
           mkdir -p deploy
           cp -r public deploy/
           cp -r .next/standalone/{*,.*} deploy/
           cp -r .next/static/ deploy/.next/static/
-      - uses: actions/upload-artifact@v4
-        with:
-          name: deploy-artifacts
-          path: deploy/
-          include-hidden-files: true
-  Build-Docker:
-    needs: Build-NodeJS
-    runs-on: ubuntu-latest
-    environment: Production
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - uses: actions/download-artifact@v4
-        with:
-          name: deploy-artifacts
-          path: deploy/
-      - name: Login to Gtihub Container Registry
+      - name: Login to Docker Registry
         uses: docker/login-action@v3
         with:
-          registry: ${{ secrets.DOCKER_HOST }}
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_KEY }}
+          registry: ${{ vars.DOCKER_HOST }}
+          username: ${{ vars.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Build and push Docker image
         uses: docker/build-push-action@v5
         with:
           push: true
           context: .
           file: Dockerfile
-          tags: ${{ secrets.DOCKER_HOST }}/${{ secrets.DOCKER_USERNAME }}/blog:latest
-  Deploy:
-    needs: Build-Docker
-    runs-on: ubuntu-latest
-    environment: Production
-    steps:
-      - name: Setup SSH
-        uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.SSH_KEY }}
-          known_hosts: unnecessary
-      - name: Deploy
+          tags: ${{ vars.DOCKER_HOST }}/caiwen-blog:latest
+      - name: Webhook
         run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-          cd ${{ secrets.DEPLOY_DIR }}
-          docker-compose down
-          docker-compose pull
-          docker-compose up -d
-          docker container prune -f
-          docker rmi -f $(docker images | grep '<none>' | awk '{print $3}')
-          docker image prune -a -f
-          EOF
+          set -e
+          response=$(curl -s -w "%{http_code}" -o response_body.txt "${{ vars.WEBHOOK }}?token=${{ secrets.WEBHOOK_TOKEN }}")
+          cat response_body.txt
+          if [ "$response" != "200" ]; then
+            echo "Webhook failed with HTTP code $response"
+            exit 1
+          fi
